/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2020;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.lang.Integer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Integer a;
        Integer b;
        Integer c;
        try {
            List<String> result = Files.readAllLines(Paths.get("./d1.txt"));
            for (var i = 0; i < result.size()-1; i++) {
                for (var x = 0; x < result.size()-1; x++) {
                    for (var z = 0; z < result.size()-1; z++) {
                        a = Integer.parseInt(result.get(i));
                        b = Integer.parseInt(result.get(x));
                        c = Integer.parseInt(result.get(z));
                        if ((a+b+c) == 2020) {
                            System.out.println(a*b*c);
                        }

                    }
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }
}
