/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2020;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.lang.Integer;

public class DayTwo {

    public static void main(String[] args) {
        String password;
        String range;
        String letter;
        Integer min;
        Integer max;
        int counter;
        int goodPassword = 0;
        try {
            List<String> result = Files.readAllLines(Paths.get("./d2.txt"));
            for (String s : result) {
                System.out.println(s);
                password = s.substring(s.indexOf(":") + 2, s.length());
                range = s.substring(0, s.indexOf(" "));
                min = Integer.parseInt(range.substring(0, range.indexOf("-")));
                max = Integer.parseInt(range.substring(range.indexOf("-")+1));
                letter = s.substring(s.indexOf(" ") + 1, s.indexOf(":"));

                if(letter.charAt(0) == password.charAt(min-1) ^
                    letter.charAt(0) == password.charAt(max-1)) {
                    goodPassword++;
                }
                /*
                counter = 0;
                for (char c : password.toCharArray()) {
                    if (c == letter.charAt(0)) {
                        counter++;
                    }
                }

                if (counter >= min && counter <= max) {
                    goodPassword++;
                }
                */
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

        System.out.println(goodPassword);

    }
}
